Repository WeakAuras/WeakAuras2, pull requests merged in 2018-12, with the labels that each got.

#996 Make frameId unique
  WeakAuras/RegionTypes/Icon.lua
Labels: 🎨 Enhancement

#999 Check for tables for default in AuthorOptions
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#1003 fix warnings in CONTRIBUTING
  CONTRIBUTING.md
Labels: ✨Housekeeping

#1005 Fix floating point error
  .luacheckrc
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#1002 Prepare for collapsible groups
  WeakAurasOptions/RegionOptions/AuraBar.lua
  WeakAurasOptions/RegionOptions/DynamicGroup.lua
  WeakAurasOptions/RegionOptions/Group.lua
  WeakAurasOptions/RegionOptions/Icon.lua
  WeakAurasOptions/RegionOptions/Model.lua
  WeakAurasOptions/RegionOptions/ProgressTexture.lua
  WeakAurasOptions/RegionOptions/Text.lua
  WeakAurasOptions/RegionOptions/Texture.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🔀 Refactor

#1008 update PR template text
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ✨Housekeeping

#1012 Misc
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#1013 fix PRD regression
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#1015 Fix login process
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#1034 Teach SetRegion to create regions initially hidden
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix
