Repository WeakAuras/WeakAuras2, pull requests merged in 2018-08, with the labels that each got.

#575 aura trigger with fullscan support remainingTime
  WeakAuras/BuffTrigger.lua
  WeakAurasOptions/BuffTrigger.lua
Labels: Awaiting Review, New Feature

#595 bugfixes
  WeakAuras/Transmission.lua
Labels: Bugfix

#594 Fix Conditions remaining time check
  WeakAuras/WeakAuras.lua
Labels: Bugfix

#578 Add group unit options
  WeakAuras/BuffTrigger.lua
  WeakAurasOptions/BuffTrigger.lua
Labels: Awaiting Review, Enhancement

#601 Fixing the Luminous Barrier CD template
  WeakAurasTemplates/TriggerTemplatesData.lua
Labels: 🐞 Bugfix

#602 fix rangecheck condition threat nil as false #598
  WeakAuras/Prototypes.lua
Labels: 🐞 Bugfix

#609 Add a "WarMode Active" load condition
  WeakAuras/Prototypes.lua
  WeakAuras/WeakAuras.lua
Labels: 🎨 Enhancement, 👆 Blizzard Bug

#627 fix autoHide for custom event w/ custom duration
  WeakAuras/GenericTrigger.lua
Labels: 🏨 Bugfix

#634 Hide child thumbnail regions when they're no longer useful
  WeakAurasOptions/RegionOptions/DynamicGroup.lua
Labels: 🏨 Bugfix

#644 revert a bad change to an earlier modernization
  WeakAuras/BuffTrigger.lua
Labels: 🏨 Bugfix

#645 Let Masque Skin the Glow
  WeakAuras/RegionTypes/Icon.lua
Labels: 🎨 Enhancement

#663 Conditions: Add AND/OR combinations to conditions
  WeakAuras/Media/Textures/bullet1.tga
  WeakAuras/Media/Textures/bullet2.tga
  WeakAuras/Media/Textures/bullet3.tga
  WeakAuras/Prototypes.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/BuffTrigger.lua
  WeakAurasOptions/ConditionOptions.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🎨 Enhancement

#667 Ensure that Options Frame exists before commiting to an import job
  WeakAuras/Transmission.lua
Labels: 🏨 Bugfix

#664 Templates smallfixes
  WeakAurasOptions/OptionsFrames/OptionsFrame.lua
  WeakAurasOptions/RegionOptions/AuraBar.lua
  WeakAurasOptions/RegionOptions/ProgressTexture.lua
  WeakAurasTemplates/TriggerTemplates.lua
Labels: 🎨 Enhancement

#679 adds worlddrop trinkets to templates
  WeakAurasTemplates/TriggerTemplatesData.lua
Labels: 🎨 Enhancement

#692 replace GetHeight with GetStringHeight
  WeakAuras/RegionTypes/Text.lua
Labels: 🏨 Bugfix
