Repository WeakAuras/WeakAuras2, pull requests merged in 2018-07, with the labels that each got.

#514 Use id instead of index in hybrid sorting
  WeakAuras/RegionTypes/DynamicGroup.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/RegionOptions/DynamicGroup.lua
Labels: Bugfix

#537 default to ratio of 1 if the aspect ratio is undefined
  WeakAuras/RegionTypes/Icon.lua
Labels: Bugfix

#490 Add "Adjust Timer" option to DBM and BigWigs timers
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
Labels: New Feature, Ready for merge

#527 allow arbitrary return values from custom text function
  WeakAuras/Prototypes.lua
  WeakAuras/RegionTypes/AuraBar.lua
  WeakAuras/RegionTypes/Icon.lua
  WeakAuras/RegionTypes/Text.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/Locales/enUS.lua
  WeakAurasOptions/RegionOptions/Icon.lua
Labels: New Feature, Ready for merge

#541 fix hiding adjusted timers on obselete timers
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
Labels: Awaiting Review, Bugfix
