Repository WeakAuras/WeakAuras2, pull requests merged in 2018-11, with the labels that each got.

#905 add minimap icon
  .pkgmeta
  WeakAuras/Profiling.lua
  WeakAuras/WeakAuras.lua
  WeakAuras/WeakAuras.toc
  WeakAuras/embeds.xml
Labels: 🎨 Enhancement

#906 handle sharing of auras with people crossrealm in same group
  WeakAuras/Transmission.lua
Labels: 🎨 Enhancement

#938 Edited README.md for concision and readability
  README.md
Labels: ✨Housekeeping

#943 make glow type option visible when glow is disabled
  WeakAurasOptions/RegionOptions/Icon.lua
Labels: 💻UI

#694 Introduce Author-defined Options
  WeakAuras/AuraEnvironment.lua
  WeakAuras/Media/Textures/collapse.tga
  WeakAuras/Media/Textures/expand.tga
  WeakAuras/Transmission.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/AuthorOptions.lua
  WeakAurasOptions/WeakAurasOptions.lua
  WeakAurasOptions/WeakAurasOptions.toc
  babelfish.lua
Labels: ✔️ Ready for Merge, 🎨 Enhancement

#950 Misc changes/fixes for author options
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#951 add space option type
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/AuthorOptions.lua
Labels: 🎨 Enhancement

#952 Misc
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix, 🔀 Refactor

#866 hide cooldown swipe & show edge on icons with stacks
  WeakAuras/RegionTypes/Icon.lua
  WeakAurasOptions/RegionOptions/Icon.lua
Labels: 🎨 Enhancement

#959 fix global leak
  WeakAuras/Transmission.lua
Labels: 🏨 Bugfix

#965 collect alpha value from color option
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#967 fix renaming causing Multipick tooltip to not show
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
Labels: 🏨 Bugfix

#976 adjust trigger.unitExists option name
  WeakAurasOptions/BuffTrigger2.lua
Labels: 💻UI

#857 cast trigger: slight rework, add multi, auto-clone and target options
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
  WeakAurasOptions/ConditionOptions.lua
Labels: 🎨 Enhancement
