Repository WeakAuras/WeakAuras2, pull requests merged in 2018-10, with the labels that each got.

#808 Fix Conditions
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#804 Change Zoom property by Condition
  WeakAuras/RegionTypes/Icon.lua
  WeakAurasOptions/ConditionOptions.lua
Labels: 🎨 Enhancement

#812 multi-selection of auras with shift modifier
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/OptionsFrames/OptionsFrame.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🎨 Enhancement

#818 Tweak dynFrame timings
  WeakAuras/WeakAuras.lua
Labels: 🏃 Performance, 🔀 Refactor

#846 Guard against mistakes in the custom variables input
  WeakAuras/GenericTrigger.lua
Labels: 🏨 Bugfix

#835 remove 2 redundant table keys
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
Labels: 🔀 Refactor

#837 fix Group & Ungroup with multi-selection
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: ⏱ Awaiting Review, 🏨 Bugfix

#755 BuffTrigger Rewrite
  WeakAuras/BuffTrigger.lua
  WeakAuras/BuffTrigger2.lua
  WeakAuras/GenericTrigger.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAuras/WeakAuras.toc
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/BuffTrigger.lua
  WeakAurasOptions/BuffTrigger2.lua
  WeakAurasOptions/GenericTrigger.lua
  WeakAurasOptions/Locales/enUS.lua
  WeakAurasOptions/WeakAurasOptions.lua
  WeakAurasOptions/WeakAurasOptions.toc
  WeakAurasTemplates/TriggerTemplates.lua
  babelfish.lua
Labels: 👩‍🔬 Work in Progress, 🔀 Refactor, 🛠 Requires Testing
