Repository WeakAuras/WeakAuras2, pull requests merged in 2018-09, with the labels that each got.

#666 cleanup trigger data
  WeakAuras/BuffTrigger.lua
  WeakAuras/GenericTrigger.lua
  WeakAuras/Transmission.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/ConditionOptions.lua
  WeakAurasOptions/GenericTrigger.lua
  WeakAurasOptions/WeakAurasOptions.lua
  WeakAurasTemplates/TriggerTemplates.lua
Labels: ✔️ Ready for Merge, 🔀Refactor

#722 delete conditions for trigger before changing optiontriggerchoices
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🏨 Bugfix

#725 Create an Aura Environment for group regions as well.
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#680 Templates Batch creation + make new auras in a group
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/OptionsFrames/OptionsFrame.lua
  WeakAurasOptions/WeakAurasOptions.lua
  WeakAurasTemplates/TriggerTemplates.lua
Labels: 🎨 Enhancement

#784 implement LibDeflate
  .gitignore
  WeakAuras/Libs/LibDeflate/LibDeflate.lua
  WeakAuras/Transmission.lua
  WeakAuras/embeds.xml
Labels: 🔀Refactor

#785 Added Condition:Attackable Target
  WeakAuras/WeakAuras.lua
Labels: 🎨 Enhancement

#798 fix WA_IterateGroupMembers again
  WeakAuras/AuraEnvironment.lua
Labels: 🏨 Bugfix
