Repository WeakAuras/WeakAuras2, pull requests merged in 2019-04, with the labels that each got.

#1266 BuffTrigger2: multiselect for buffclass
  WeakAuras/BuffTrigger2.lua
  WeakAuras/Transmission.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/BuffTrigger2.lua
  WeakAurasOptions/OptionsFrames/ImportExport.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🎨 Enhancement

#1270 fix auras with strata=TOOLTIP highjacking cursor's clicks
  WeakAuras/RegionTypes/AuraBar.lua
  WeakAuras/RegionTypes/Icon.lua
  WeakAuras/RegionTypes/RegionPrototype.lua
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/OptionsFrames/MoverSizer.lua
  WeakAurasOptions/OptionsFrames/OptionsFrame.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🏨 Bugfix

#1281 regenerate option name and key if necessary
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#1286 collect errors from login thread
  WeakAuras/WeakAuras.lua
Labels: ✨Housekeeping

#1272 Custom Grow & Sort
  WeakAuras/AuraEnvironment.lua
  WeakAuras/RegionTypes/DynamicGroup.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/OptionsFrames/TextEditor.lua
  WeakAurasOptions/RegionOptions/DynamicGroup.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: ✔️ Ready to Merge, 🎨 Enhancement

#1300 Fix Anchoring issue with dynamic group when using children that have SELECTFRAME anchorFrameType
  WeakAuras/RegionTypes/DynamicGroup.lua
Labels: 🏨 Bugfix

#1307 add new feature indicator
  WeakAuras/Prototypes.lua
Labels: ✨Housekeeping

#1301 collapsible headers for conditions
  WeakAurasOptions/ConditionOptions.lua
Labels: 🎨 Enhancement, 💻UI

#1312 Add a Exact Spell Id option to Spell Known triggers
  WeakAuras/Prototypes.lua
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#1305 remove stale feature indicators
  WeakAuras/RegionTypes/Icon.lua
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/ActionOptions.lua
  WeakAurasOptions/OptionsFrames/OptionsFrame.lua
  WeakAurasOptions/RegionOptions/Icon.lua
  WeakAurasOptions/WeakAurasOptions.lua
  WeakAurasTemplates/TriggerTemplates.lua
Labels: ✨Housekeeping

#1315 fix WatchUnitChange sending lowercase unit event #1313
  WeakAuras/GenericTrigger.lua
Labels: 🏨 Bugfix
