Repository WeakAuras/WeakAuras2, pull requests merged in 2019-08, with the labels that each got.

#1509 misc
  WeakAuras/WeakAuras.lua
Labels: 🎨 Enhancement, 🔀 Refactor

#1513 fix SetItemRef taint
  WeakAuras/Transmission.lua
Labels: 🏨 Bugfix

#1515 make profiling data accessible from 3rd party
  WeakAuras/Profiling.lua
Labels: 🎨 Enhancement

#1514 Multiunits
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
  WeakAurasOptions/GenericTrigger.lua
Labels: 🎨 Enhancement

#1510 Add history collection
  WeakAuras/History.lua
  WeakAuras/Transmission.lua
  WeakAuras/WeakAuras.lua
  WeakAuras/WeakAuras.toc
  babelfish.lua
Labels: ✔️ Ready to Merge, 🎨 Enhancement

#1567 allow string custom option to give a multiline edit box
  WeakAuras/Types.lua
  WeakAurasOptions/AuthorOptions.lua
Labels: 🎨 Enhancement

#1564 classic combo points: fix division per 0 for class with no combo points
  WeakAuras/Prototypes.lua
Labels: 🏨 Bugfix

#1569 classic: use LibClassicCasterino for cast trigger
  .pkgmeta-classic
  WeakAuras/Prototypes.lua
  WeakAuras/embeds.xml
Labels: 🎨 Enhancement

#1573 remove stale feature indicators
  WeakAuras/BuffTrigger2.lua
  WeakAuras/Prototypes.lua
  WeakAuras/RegionTypes/Icon.lua
  WeakAuras/Types.lua
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/BuffTrigger2.lua
  WeakAurasOptions/RegionOptions/DynamicGroup.lua
Labels: ✨Housekeeping

#1574 move *new* glow feature indicators into subtree
  WeakAuras/RegionTypes/Icon.lua
Labels: ✨Housekeeping

#1585 default to height of 1
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#1590 Increase moversizer strata
  WeakAurasOptions/OptionsFrames/MoverSizer.lua
Labels: 🏨 Bugfix

#1588 Rewrite Border as a sub element
  WeakAuras/RegionTypes/AuraBar.lua
  WeakAuras/SubRegionTypes/Border.lua
  WeakAuras/WeakAuras.lua
  WeakAuras/WeakAuras.toc
  WeakAurasOptions/RegionOptions/AuraBar.lua
  WeakAurasOptions/SubRegionOptions/Border.lua
  WeakAurasOptions/SubRegionOptions/SubRegionCommon.lua
  WeakAurasOptions/SubRegionOptions/SubText.lua
  WeakAurasOptions/WeakAurasOptions.lua
  WeakAurasOptions/WeakAurasOptions.toc
Labels: 🎨 Enhancement

#1597 fix migration
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix, 📊Data Issue

#1605 Fix drawLayer calculation
  WeakAuras/RegionTypes/ProgressTexture.lua
Labels: 🏨 Bugfix
