Repository WeakAuras/WeakAuras2, pull requests merged in 2019-03, with the labels that each got.

#1220 guard against nil
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#1221 set option max to the *max*, not the min
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#1226 Allow duplicate on groups
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🎨 Enhancement

#1231 Bugs
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#1242 Add Dynamic Group grid layout
  WeakAuras/RegionTypes/DynamicGroup.lua
  WeakAuras/Types.lua
  WeakAurasOptions/RegionOptions/DynamicGroup.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🎨 Enhancement

#1254 Add alignment snapping for auras and groups
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/OptionsFrames/MoverSizer.lua
  WeakAurasOptions/OptionsFrames/OptionsFrame.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🎨 Enhancement, 💻UI
