Repository WeakAuras/WeakAuras2, pull requests merged in 2019-06, with the labels that each got.

#1375 Action Usable trigger: Fix nil comparison error with spellCount
  WeakAuras/Prototypes.lua
Labels: 🏨 Bugfix

#1379 Fix inserting > 32bit values into the name field
  WeakAuras/BuffTrigger2.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/BuffTrigger2.lua
  WeakAurasOptions/Cache.lua
Labels: 🏨 Bugfix

#1295 Option groups
  WeakAuras/Media/Textures/downleft.tga
  WeakAuras/Media/Textures/downright.tga
  WeakAuras/Media/Textures/upleft.tga
  WeakAuras/Media/Textures/upright.tga
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/AuthorOptions.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: ✔️ Ready to Merge

#1396 delete the currently selected entry
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#1407 expose dynamic group helper functions
  WeakAuras/RegionTypes/DynamicGroup.lua
Labels: 🎨 Enhancement

#1426 use file id for lich king apocalypse
  WeakAuras/Types.lua
Labels: 🏨 Bugfix
