Repository WeakAuras/WeakAuras2, pull requests merged in 2019-09, with the labels that each got.

#1653 now that sticky.duration is gone, we can optimize this code path a bit
  WeakAuras/RegionTypes/RegionPrototype.lua
Labels: 🔀 Refactor

#1626 don't load environment of children for custom anchor function
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#1649 Improve Weapon Enchant Trigger
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
Labels: 🎨 Enhancement

#1665 use min/max/etc for range slider
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#1676 don't package modelpaths for WeakAuras classic
  .pkgmeta-classic
Labels: ✨Housekeeping

#1648 Add Experimental Repair Tool
  WeakAuras/History.lua
  WeakAuras/Locales/enUS.lua
  WeakAuras/WeakAuras.lua
Labels: 🎨 Enhancement, 📊Data Issue

#1646 use GitHub Actions v2 instead of TravisCI
  .editorconfig
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .travis.yml
  README.md
Labels: ✨Housekeeping
