Repository WeakAuras/WeakAuras2, pull requests merged in 2019-05, with the labels that each got.

#1317 don't collapse conditions by default for now
  WeakAurasOptions/ConditionOptions.lua
Labels: 💻UI

#1311 New glow options for icons
  WeakAuras/RegionTypes/Icon.lua
  WeakAurasOptions/RegionOptions/Icon.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🎨 Enhancement

#1334 fix WeakAuras.CountWagoUpdates
  WeakAuras/WeakAuras.lua
Labels: 🐛 Bug

#1325 Filter generic & custom triggers with CLEU and UNIT_* events before xpcall(data.triggerFunc, ...)
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/GenericTrigger.lua
Labels: 🔀 Refactor, 🛠 Requires Testing

#1351 don't bother positioning children if there are none active
  WeakAuras/RegionTypes/DynamicGroup.lua
Labels: 🏨 Bugfix

#1359 fix DBM and BW Timers message filter
  WeakAuras/Prototypes.lua
Labels: 🏨 Bugfix

#1364 use sane values for y offset parameters
  WeakAuras/RegionTypes/Icon.lua
Labels: 🏨 Bugfix
