Repository WeakAuras/WeakAuras2, pull requests merged in 2019-01, with the labels that each got.

#1077 Allow custom options to format text
  WeakAuras/Transmission.lua
  WeakAurasOptions/AuthorOptions.lua
Labels: 🎨 Enhancement

#1085 fix wago menu
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
Labels: ✔️ Ready to Merge, 🎨 Enhancement

#1098 fix default values for multiselect
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#1116 improve coroutine error handling
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#1115 adds battle for dazar'alor raid trinkets to templates
  WeakAurasTemplates/TriggerTemplatesData.lua
Labels: ✨Housekeeping, 🎨 Enhancement

#1117 guard against invalid inputs to auraspellids
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🏨 Bugfix

#1136 Don't show a default value for unit type condition #1135
  WeakAurasOptions/ConditionOptions.lua
Labels: 🏨 Bugfix
