Repository WeakAuras/WeakAuras2, pull requests merged in 2019-07, with the labels that each got.

#1435 delete corrupted custom options
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#1347 WoW Classic compatibility
  .luacheckrc
  .pkgmeta-classic
  .travis.yml
  WeakAuras/BuffTrigger.lua
  WeakAuras/BuffTrigger2.lua
  WeakAuras/GenericTrigger.lua
  WeakAuras/Init.lua
  WeakAuras/Prototypes.lua
  WeakAuras/RegionTypes/Model.lua
  WeakAuras/RegionTypes/ProgressTexture.lua
  WeakAuras/RegionTypes/RegionPrototype.lua
  WeakAuras/RegionTypes/Texture.lua
  WeakAuras/Transmission.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAuras/WeakAuras.toc
  WeakAuras/embeds.xml
  WeakAurasModelPaths/WeakAurasModelPaths.toc
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasTextureButton.lua
  WeakAurasOptions/RegionOptions/AuraBar.lua
  WeakAurasOptions/RegionOptions/Icon.lua
  WeakAurasOptions/RegionOptions/Model.lua
  WeakAurasOptions/RegionOptions/ProgressTexture.lua
  WeakAurasOptions/RegionOptions/Texture.lua
  WeakAurasOptions/WeakAurasOptions.toc
  WeakAurasTemplates/TriggerTemplates.lua
  WeakAurasTemplates/TriggerTemplatesData.lua
  WeakAurasTemplates/WeakAurasTemplates.toc
Labels: ⏱ Awaiting Review, ⚰️Classic, 🎨 Enhancement

#913 Rework text replacements to allow %#.variable
  WeakAuras/AuraEnvironment.lua
  WeakAuras/BuffTrigger.lua
  WeakAuras/BuffTrigger2.lua
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
  WeakAuras/RegionTypes/AuraBar.lua
  WeakAuras/RegionTypes/DynamicGroup.lua
  WeakAuras/RegionTypes/Group.lua
  WeakAuras/RegionTypes/Icon.lua
  WeakAuras/RegionTypes/Model.lua
  WeakAuras/RegionTypes/ProgressTexture.lua
  WeakAuras/RegionTypes/RegionPrototype.lua
  WeakAuras/RegionTypes/Text.lua
  WeakAuras/RegionTypes/Texture.lua
  WeakAuras/SubRegionTypes/SubText.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAuras/WeakAuras.toc
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
  WeakAurasOptions/BuffTrigger.lua
  WeakAurasOptions/BuffTrigger2.lua
  WeakAurasOptions/OptionsFrames/OptionsFrame.lua
  WeakAurasOptions/RegionOptions/AuraBar.lua
  WeakAurasOptions/RegionOptions/Icon.lua
  WeakAurasOptions/RegionOptions/ProgressTexture.lua
  WeakAurasOptions/RegionOptions/Text.lua
  WeakAurasOptions/RegionOptions/Texture.lua
  WeakAurasOptions/SubRegionOptions/SubText.lua
  WeakAurasOptions/WeakAurasOptions.lua
  WeakAurasOptions/WeakAurasOptions.toc
  babelfish.lua
Labels: 🎨 Enhancement

#1490 resort any region which is changed
  WeakAuras/BuffTrigger.lua
  WeakAuras/BuffTrigger2.lua
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix
