Repository WeakAuras/WeakAuras2, pull requests merged in 2020-08, with the labels that each got.

#2357 defend against silly user errors more
  WeakAuras/RegionTypes/DynamicGroup.lua
Labels: 🏨 Bugfix

#2371 clear all points on frameChooserBox first
  WeakAurasOptions/OptionsFrames/FrameChooser.lua
Labels: 🏨 Bugfix

#2346 Update "The Pencil"
  WeakAuras/Media/Textures/gear.tga
  WeakAuras/Media/Textures/geardown.tga
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasExpandAnchor.lua
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasExpandSmall.lua
  WeakAurasOptions/ConditionOptions.lua
  WeakAurasOptions/LoadOptions.lua
  WeakAurasOptions/RegionOptions/Icon.lua
  WeakAurasOptions/RegionOptions/Text.lua
  WeakAurasOptions/SubRegionOptions/Glow.lua
  WeakAurasOptions/SubRegionOptions/SubText.lua
  WeakAurasOptions/SubRegionOptions/Tick.lua
  WeakAurasOptions/WeakAurasOptions.lua
  WeakAurasOptions/WeakAurasOptions.toc
Labels: 💻UI/UX

#2379 re-enable model region for classic
  .github/workflows/pull_request.yml
  .pkgmeta
  .pkgmeta-classic
  WeakAuras/RegionTypes/Model.lua
  WeakAuras/SubRegionTypes/BarModel.lua
  WeakAuras/WeakAuras.lua
  WeakAuras/WeakAuras.toc
  WeakAurasModelPaths/ModelPathsClassic.lua
  WeakAurasModelPaths/WeakAurasModelPaths.toc
  WeakAurasOptions/OptionsFrames/OptionsFrame.lua
  WeakAurasOptions/RegionOptions/Model.lua
  WeakAurasOptions/SubRegionOptions/BarModel.lua
  WeakAurasOptions/WeakAurasOptions.toc
Labels: ⏱ Awaiting Review, ⚰️Classic
