Repository WeakAuras/WeakAuras2, pull requests merged in 2020-04, with the labels that each got.

#2085 Allow WA Updates from chat links.
  WeakAuras/Transmission.lua
  WeakAurasOptions/WeakAurasOptions.lua
Labels: 🎨 Enhancement

#2080 Eased translate animations
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
Labels: 🎨 Enhancement

#2070 [WIP] Auto re-anchor unitframes & slightly different anchors for nameplates addons
  WeakAuras/RegionTypes/DynamicGroup.lua
  WeakAuras/WeakAuras.lua
Labels: 🎨 Enhancement, 👩‍🔬 Work in Progress

#2087 Universal animation easing
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/AnimationOptions.lua
Labels: 🎨 Enhancement

#2121 Add missing migration for action's glow_type
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#2139 BT2 Fix Multi by adjusting it to recent changes
  WeakAuras/BuffTrigger2.lua
Labels: 🏨 Bugfix

#2101 Profiling Improvements
  WeakAuras/Profiling.lua
  WeakAuras/WeakAuras.lua
Labels: 🎨 Enhancement
