Repository WeakAuras/WeakAuras2, pull requests merged in 2020-02, with the labels that each got.

#1947 Add Trapeze To Shapes
  WeakAuras/Media/Textures/Trapeze.tga
  WeakAuras/Types.lua
Labels: 🎨 Enhancement

#1978 add 'reset entry' button to arrays in user mode
  WeakAuras/Media/Textures/reset.tga
  WeakAurasOptions/AuthorOptions.lua
Labels: 🎨 Enhancement

#1996 compare value to value, not table containing value
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#1949 Show realtime visual graph of profiling
  WeakAuras/Bindings.xml
  WeakAuras/Init.lua
  WeakAuras/Profiling.lua
  WeakAuras/WeakAuras.lua
Labels: ⏱ Awaiting Review, 🎨 Enhancement

#2009 clear authormode on any child imports too
  WeakAuras/Transmission.lua
Labels: 🏨 Bugfix
