Repository WeakAuras/WeakAuras2, pull requests merged in 2020-05, with the labels that each got.

#2165 refactor anchor & glow to unitframe monitoring
  WeakAuras/WeakAuras.lua
Labels: ⏱ Awaiting Review, 🏨 Bugfix

#2176 Add snippets
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasSnippetButton.lua
  WeakAurasOptions/OptionsFrames/TextEditor.lua
  WeakAurasOptions/WeakAurasOptions.toc
Labels: 🎨 Enhancement

#2199 fix nil error
  WeakAuras/Types.lua
Labels: 🏨 Bugfix
