Repository WeakAuras/WeakAuras2, pull requests merged in 2020-07, with the labels that each got.

#2228 Threat Situation trigger rework and enable it for WoW 1.13.5
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
Labels: ✔️ Ready to Merge

#2235 Add LibSerialize
  .pkgmeta
  .pkgmeta-classic
  WeakAuras/ArchiveTypes/Repository.lua
  WeakAuras/History.lua
  WeakAuras/Transmission.lua
  WeakAuras/embeds.xml
Labels: 🎨 Enhancement

#2293 drop "old" new feature indicators
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
  WeakAurasOptions/BuffTrigger2.lua
  WeakAurasOptions/RegionOptions/DynamicGroup.lua
  WeakAurasOptions/RegionOptions/Group.lua
Labels: ✨Housekeeping

#2289 Make CD Widget functional when using a static progress type on an icon aura.
  WeakAuras/RegionTypes/Icon.lua
Labels: 🎨 Enhancement

#2310 add fullCircle option
  WeakAuras/RegionTypes/DynamicGroup.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/RegionOptions/DynamicGroup.lua
Labels: 🎨 Enhancement

#2313 Tick improvements
  WeakAuras/SubRegionTypes/Tick.lua
  WeakAurasOptions/SubRegionOptions/Tick.lua
Labels: 🎨 Enhancement

#2340 fix pvp talents
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix
