Repository WeakAuras/WeakAuras2, pull requests merged in 2020-01, with the labels that each got.

#1885 remember update preferences for each aura
  .luacheckrc
  WeakAuras/Transmission.lua
  WeakAuras/Types.lua
Labels: ✔️ Ready to Merge, 🎨 Enhancement

#1868 Custom Options Author Names Tweaks
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#1856 classic: workaround GetSpellCount change in 1.13.03 #1849
  .pkgmeta-classic
  WeakAuras/GenericTrigger.lua
  WeakAuras/embeds.xml
Labels: ⏱ Awaiting Review, ⚰️Classic

#1850 Add WeakAurasArchive
  .luacheckrc
  .pkgmeta
  .pkgmeta-classic
  WeakAuras/ArchiveTypes/Repository.lua
  WeakAuras/History.lua
  WeakAuras/WeakAuras.lua
  WeakAuras/WeakAuras.toc
  WeakAuras/embeds.xml
  WeakAurasArchive/WeakAurasArchive.lua
  WeakAurasArchive/WeakAurasArchive.toc
Labels: ✔️ Ready to Merge, 🎨 Enhancement

#1919 rewrite Set to not be broken
  WeakAuras/ArchiveTypes/Repository.lua
Labels: 🏨 Bugfix

#1907 add ComposeSorts and CompareRegionData helpers
  WeakAuras/RegionTypes/DynamicGroup.lua
  WeakAurasOptions/RegionOptions/DynamicGroup.lua
Labels: 🎨 Enhancement

#1924 remove babelfish requirement
  CONTRIBUTING.md
Labels: ✨Housekeeping

#1934 lower frequency of ITEM_COUNT_UPDATE for Item Count trigger fixes #1933
  WeakAuras/GenericTrigger.lua
Labels: 🏨 Bugfix

#1943 swallow stacksfunc errors
  WeakAuras/GenericTrigger.lua
Labels: 🏨 Bugfix
