Repository WeakAuras/WeakAuras2, pull requests merged in 2021-12, with the labels that each got.

#3369 yeet duplicate keys in custom options
  .gitignore
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#3379 check that option key exists before writing
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#3376 Fix updating of PVP Talents
  WeakAuras/WeakAuras.lua
Labels: ✔️ Ready to Merge

#3394 subregions tweaks
  WeakAuras/Modernize.lua
  WeakAuras/RegionTypes/AuraBar.lua
  WeakAuras/RegionTypes/Icon.lua
  WeakAuras/RegionTypes/Model.lua
  WeakAuras/RegionTypes/ProgressTexture.lua
  WeakAuras/RegionTypes/Text.lua
  WeakAuras/RegionTypes/Texture.lua
  WeakAuras/RegionTypes/stopmotion.lua
  WeakAuras/SubRegionTypes/Background.lua
  WeakAuras/SubRegionTypes/Model.lua
  WeakAuras/WeakAuras.lua
  WeakAuras/WeakAuras.toc
  WeakAurasOptions/RegionOptions/AuraBar.lua
  WeakAurasOptions/SubRegionOptions/Background.lua
  WeakAurasOptions/SubRegionOptions/Model.lua
  WeakAurasOptions/WeakAurasOptions.toc
  WeakAurasTemplates/TriggerTemplates.lua
Labels: 👩‍🔬 Work in Progress
