Repository WeakAuras/WeakAuras2, pull requests merged in 2022-08, with the labels that each got.

#3699 Add a framework for built in trigger updates to fire into custom triggers
  WeakAuras/BuffTrigger2.lua
  WeakAuras/GenericTrigger.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/GenericTrigger.lua
  WeakAurasOptions/Locales/enUS.lua
Labels: 🎨 Enhancement, 👩‍🔬 Work in Progress

#3730 Wrath Talent load condition rework
  WeakAuras/Prototypes.lua
  WeakAuras/Types_Retail.lua
  WeakAuras/Types_Wrath.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasMiniTalent_Wrath.lua
  WeakAurasOptions/LoadOptions.lua
  WeakAurasOptions/WeakAurasOptions_Wrath.toc
Labels: ⏱ Awaiting Review, 💻UI/UX

#3775 Smallfix
  WeakAuras/Prototypes.lua
Labels: 🧟‍♂‍ WOTLK
