Repository WeakAuras/WeakAuras2, pull requests merged in 2023-02, with the labels that each got.

#4266 softenemy/friend support in BT2
  .luacheckrc
  WeakAuras/BuffTrigger2.lua
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/BuffTrigger2.lua
Labels: 🎨 Enhancement

#4315 fix ignored value checks
  WeakAurasOptions/OptionsFrames/Update.lua
Labels: 🏨 Bugfix

#4244 Aura trigger: use new API for retail
  .luacheckrc
  WeakAuras/BuffTrigger2.lua
  WeakAuras/WeakAuras.lua
Labels: ⏱ Awaiting Review
