Repository WeakAuras/WeakAuras2, pull requests merged in 2023-01, with the labels that each got.

#4205 only run sort/grow when interesting state changes happen
  WeakAuras/Modernize.lua
  WeakAuras/RegionTypes/DynamicGroup.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/RegionOptions/DynamicGroup.lua
Labels: 🎨 Enhancement, 🏃 Performance Issue

#4239 be more careful about removing subscribers
  WeakAuras/SubscribableObject.lua
Labels: 🏨 Bugfix

#4252 fix custom sort
  WeakAuras/Modernize.lua
  WeakAuras/RegionTypes/DynamicGroup.lua
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#4270 update dragonflight talents tree for 10.0.5.47660
  WeakAuras/Types_Retail.lua
Labels: ✨Housekeeping

#4273 add stagger stat
  WeakAuras/Prototypes.lua
Labels: 🎨 Enhancement
