Repository WeakAuras/WeakAuras2, pull requests merged in 2024-04, with the labels that each got.

#4969 add a label to bool property changes
  WeakAurasOptions/ConditionOptions.lua
Labels: 🎨 Enhancement

#4952 Add GitHub Actions workflows for Release Notifications
  .github/scripts/generate_twitter_post.py
  .github/scripts/test_files/large_changelog_example.md
  .github/workflows/release_notifications.yml
  .github/workflows/release_notifications_manual_tests.yml
  .github/workflows/release_notifications_setup.md
Labels: ✨Housekeeping

#4968 Faction Reputation trigger rework
  .luacheckrc
  WeakAuras/Prototypes.lua
Labels: 🎨 Enhancement

#4987 Add missing difficulty IDs from latest WoW patch
  WeakAuras/Types.lua
Labels: ✨Housekeeping

#4992 fix some more type annotations
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
Labels: 🏨 Bugfix

#5007 improve AddMany data flow
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#4917 add Location trigger
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/LoadOptions.lua
Labels: 🎨 Enhancement

#5019 only use whisper comms if target is on the actually same server
  WeakAuras/Transmission.lua
Labels: 🏨 Bugfix
