Repository WeakAuras/WeakAuras2, pull requests merged in 2024-02, with the labels that each got.

#4862 move type checking code for WeakAurasArchive
  WeakAuras/WeakAuras.lua
  WeakAurasArchive/WeakAurasArchive.lua
  WeakAurasArchive/WeakAurasArchive.toc
  WeakAurasArchive/WeakAurasArchive_Vanilla.toc
  WeakAurasArchive/WeakAurasArchive_Wrath.toc
Labels: 🏨 Bugfix

#4872 harden WeakAuras against bad migrations
  WeakAuras/AnchorToWeakAuras.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/OptionsFrames/MoverSizer.lua
Labels: 🏨 Bugfix, 📊Data Issue

#4877 fix buildType detection
  .github/workflows/build-beta.yml
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  WeakAuras/Init.lua
Labels: 🏨 Bugfix

#4846 Player Location: Parent Zone support
  WeakAuras/Prototypes.lua
  WeakAuras/WeakAuras.lua
Labels: 🎨 Enhancement
