Repository WeakAuras/WeakAuras2, pull requests merged in 2024-05, with the labels that each got.

#5014 Prepare for the removal of deprecated functions
  .luacheckrc
  WeakAuras/AuraEnvironment.lua
  WeakAuras/BuffTrigger2.lua
  WeakAuras/GenericTrigger.lua
  WeakAuras/Init.lua
  WeakAuras/Prototypes.lua
  WeakAuras/Types.lua
  WeakAuras/WeakAuras.lua
  WeakAurasOptions/LoadOptions.lua
  WeakAurasOptions/OptionsFrames/OptionsFrame.lua
  WeakAurasOptions/TriggerOptions.lua
  WeakAurasOptions/WeakAurasOptions.lua
  WeakAurasTemplates/TriggerTemplatesData.lua
  WeakAurasTemplates/TriggerTemplatesDataClassicEra.lua
  WeakAurasTemplates/TriggerTemplatesDataWrath.lua
Labels: 👩‍🔬 Work in Progress, 🔜Future Issue

#5037 advertise a link to an experimental build, if one exists
  .github/pr-commenter.yml
  .github/workflows/pull_request.yml
Labels: ✨Housekeeping

#5052 only upload & advertise build artifact if triggering actor has a write bit
  .github/pr-commenter.yml
  .github/workflows/pull_request.yml
Labels: ✨Housekeeping

#5034 ensure we always compute the correct rect for a dynamic group
  WeakAuras/RegionTypes/DynamicGroup.lua
  WeakAuras/RegionTypes/RegionPrototype.lua
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#5056 AuraBar: add some alias textures, and option to use texture picker
  WeakAuras/RegionTypes/AuraBar.lua
  WeakAuras/Types.lua
  WeakAurasOptions/AceGUI-Widgets/WeakAurasStatusbarAtlasWidget.lua
  WeakAurasOptions/RegionOptions/AuraBar.lua
  WeakAurasOptions/WeakAurasOptions.toc
  WeakAurasOptions/WeakAurasOptions_Cata.toc
  WeakAurasOptions/WeakAurasOptions_Vanilla.toc
  WeakAurasOptions/WeakAurasOptions_Wrath.toc
Labels: 🆕 Feature Preview

#5066 always ReAnchor() if isRestricted, not just if numVisible > 0
  WeakAuras/RegionTypes/DynamicGroup.lua
Labels: 🏨 Bugfix

#5072 explicitly checkout head ref
  .github/workflows/pull_request.yml
Labels: ✨Housekeeping

#5075 be more careful about keeping nameSource accurate
  WeakAurasOptions/AuthorOptions.lua
Labels: 🏨 Bugfix

#5091 LibSpecialization support on Cataclysm
  WeakAuras/BuffTrigger2.lua
  WeakAuras/GenericTrigger.lua
  WeakAuras/LibSpecializationWrapper.lua
  WeakAuras/Prototypes.lua
  WeakAuras/WeakAuras.lua
  WeakAuras/WeakAuras_Cata.toc
  WeakAurasOptions/BuffTrigger2.lua
Labels: 🆕 Feature Preview
