Repository WeakAuras/WeakAuras2, pull requests merged in 2024-08, with the labels that each got.

#5306 WIP Templates update
  WeakAurasTemplates/TriggerTemplatesData.lua
Labels: 👩‍🔬 Work in Progress

#5322 add a line to custom code errors to identify the stack trace
  WeakAuras/WeakAuras.lua
Labels: 🎨 Enhancement

#5357 close a hole in the sandbox
  WeakAuras/AuraEnvironment.lua
  WeakAurasOptions/OptionsFrames/TextEditor.lua
Labels: 🏨 Bugfix
