Repository WeakAuras/WeakAuras2, pull requests merged in 2024-06, with the labels that each got.

#5108 Remove legacy GetCurrencyInfo code for Cataclysm
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
Labels: 🏨 Bugfix

#5150 use table.concat to build various function strings
  WeakAuras/BuffTrigger2.lua
  WeakAuras/Conditions.lua
  WeakAuras/GenericTrigger.lua
  WeakAuras/WeakAuras.lua
Labels: 🎨 Enhancement, 🏃 Performance Issue

#5083 hide dynFrame if combat starts with living threads
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix, 🏃 Performance Issue

#5159 Combo Ponts Trigger: Add COMBO_TARGET_CHANGED for Cataclysm
  WeakAuras/GenericTrigger.lua
  WeakAuras/Prototypes.lua
Labels: 🆕 Feature Preview
