Repository WeakAuras/WeakAuras2, pull requests merged in 2024-03, with the labels that each got.

#4899 only obliterate whispers when we actually find a weakauras link in them
  WeakAuras/Transmission.lua
Labels: 🏨 Bugfix

#4915 fix login deferral logic for AnchorFrame
  WeakAuras/WeakAuras.lua
Labels: 🏨 Bugfix

#4910 update issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: ✨Housekeeping

#4916 Add DBM_TimerUpdateIcon event listener
  WeakAuras/BossMods.lua
Labels: 🎨 Enhancement
