Repository WeakAuras/WeakAuras2, pull requests merged in 2025-02, with the labels that each got.

#5668 only nag user on /reload or /camp, instead of every loading screen
  WeakAuras/WeakAuras.lua
Labels: 🎨 Enhancement

#5683 deduplicate localization phrases
  babelfish.lua
Labels: ✨Housekeeping

#5195 Allstates helper methods
  WeakAuras/GenericTrigger.lua
  WeakAuras/TSUHelpers.lua
  WeakAuras/WeakAuras.lua
  WeakAuras/WeakAuras.toc
  WeakAuras/WeakAuras_Cata.toc
  WeakAuras/WeakAuras_Vanilla.toc
  WeakAurasOptions/OptionsFrames/TextEditor.lua
Labels: 🆕 Feature Preview

#5702 put the mixins in private exec_env too
  WeakAuras/AuraEnvironment.lua
Labels: 🏨 Bugfix
