Repository WeakAuras/WeakAuras2, pull requests merged in 2025-03, with the labels that each got.

#5713 remove spurious enUS translations
  WeakAurasOptions/Locales/enUS.lua
Labels: 🆕 Feature Preview

#5747 RENOWN_LEVEL_LABEL globalstring changed with 11.1
  WeakAuras/Prototypes.lua
Labels: 🏨 Bugfix

#5706 Bossmod triggers show timers regardless of bossmod settings
  .luacheckrc
  WeakAuras/BossMods.lua
  WeakAuras/Modernize.lua
  WeakAuras/WeakAuras.lua
Labels: ⏱ Awaiting Review

#5754 pull enUS locale for Options from CF
  WeakAurasOptions/Locales/enUS.lua
Labels: 🆕 Feature Preview
